Language: ruby
- cache: bundler

branches:
  only:
    - master
rvm:
  2.4.1

before_script:
  - yes | gem update --system --force
  - gem install bundler
  - chmod +x ./script/cibuild

script: ./script/cibuild

exclude: [vendor]
sudo: false
