Language: ruby
cache: bundler

branches:
  only:
    - master
rvm:
  2.4.1

before_script:
  - gem install bundler:1.17.3
  - bundle update --bundler
  - chmod +x ./script/cibuild

script: ./script/cibuild

exclude: [vendor]
sudo: false
