collections:
  staff:
    output: true
  issues:
    output: true
    future: true
    permalink: "/issues/:year-:month-:name:output_ext"
  videocategories:
    output: true
  videos:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "staff"
    values:
      layout: "staff"
      title: "{{ page.displayname }}"
      image: "/assets/img/staff/defaultprofile.png"
  - scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"
  - scope:
      path: ""
    values:
      layout: "base-title"
  - scope:
      path: ""
      type: "videocategories"
    values:
      layout: "videocategory"